# Generated by Django 3.2.12 on 2022-04-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representante', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('ruc_empresa', models.CharField(default='0', max_length=50)),
                ('potreros', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('cantidad_M', models.IntegerField(blank=True, null=True)),
                ('cantidad_H', models.IntegerField(blank=True, null=True)),
                ('pesoTotal', models.IntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='partediario.categoria', verbose_name='Categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='lluvia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_central', models.PositiveSmallIntegerField(verbose_name="Cant. de mm's de lluvia en la Central:")),
                ('mm_retiro', models.PositiveSmallIntegerField(verbose_name="Cant. de mm's de lluvia en el Retiro:")),
                ('evento', models.CharField(max_length=50, verbose_name='Otro evento:')),
            ],
        ),
        migrations.CreateModel(
            name='opcionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='opcionSanitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Opciones de Sanitacion',
            },
        ),
        migrations.CreateModel(
            name='parteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha Creada')),
                ('Entradas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.entradas', verbose_name='Entradas')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.empresa', verbose_name='Empresa')),
                ('entrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.entrada', verbose_name='Entrada')),
                ('lluvia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.lluvia', verbose_name='Lluvias')),
            ],
        ),
        migrations.CreateModel(
            name='Potrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franja', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salidas', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Salidas',
            },
        ),
        migrations.CreateModel(
            name='Superficie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_totales', models.CharField(max_length=50)),
                ('has_utiles', models.CharField(max_length=50)),
                ('actividad', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superficies', to='partediario.empresa', verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='sanitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potrero', models.IntegerField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=100)),
                ('elemento', models.ManyToManyField(to='partediario.opcionSanitacion')),
                ('parteDiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanitacion', to='partediario.partediario', verbose_name='Sanitacion/Vacunacion')),
            ],
            options={
                'verbose_name_plural': 'Sanitaciones',
            },
        ),
        migrations.CreateModel(
            name='salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('causa', models.CharField(max_length=50)),
                ('categoria_madre', models.ManyToManyField(to='partediario.Categoria')),
                ('salidas', models.ManyToManyField(to='partediario.Salidas')),
            ],
        ),
        migrations.CreateModel(
            name='rotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potrero_inicial', models.CharField(max_length=50)),
                ('potrero_final', models.CharField(max_length=50)),
                ('parteDiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotacion', to='partediario.partediario', verbose_name='Rotacion')),
            ],
            options={
                'verbose_name_plural': 'Rotaciones',
            },
        ),
        migrations.CreateModel(
            name='recorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potrero', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=120)),
                ('parteDiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorrida', to='partediario.partediario', verbose_name='Recorrida')),
            ],
        ),
        migrations.CreateModel(
            name='recategorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('categoria_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final', to='partediario.categoria', verbose_name='Recategorizacion Final')),
                ('categoria_inicial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inicial', to='partediario.categoria', verbose_name='Recategorizacion Inicial')),
                ('parteDiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recategorizacion', to='partediario.partediario', verbose_name='Recategorizacion')),
            ],
            options={
                'verbose_name_plural': 'Recategorizaciones',
            },
        ),
        migrations.CreateModel(
            name='pesaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('peso_minimo', models.IntegerField(blank=True, null=True)),
                ('peso_maximo', models.IntegerField(blank=True, null=True)),
                ('categoria', models.ManyToManyField(to='partediario.Categoria')),
                ('parteDiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesaje', to='partediario.partediario', verbose_name='Pesajes')),
            ],
        ),
        migrations.AddField(
            model_name='partediario',
            name='salida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.salida', verbose_name='Salida'),
        ),
        migrations.AddField(
            model_name='partediario',
            name='salidas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.salidas', verbose_name='Salidas'),
        ),
        migrations.CreateModel(
            name='otraActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('actividad_realizada', models.ManyToManyField(to='partediario.opcionActividad')),
                ('categoria', models.ManyToManyField(to='partediario.Categoria')),
                ('parteDiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Otra', to='partediario.partediario', verbose_name='Otros')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=50)),
                ('pesocab', models.CharField(max_length=50)),
                ('categoria', models.ManyToManyField(to='partediario.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='entrada',
            name='entradas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='partediario.entradas', verbose_name='Entradas'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='Inventario_de_Empresa',
            field=models.ManyToManyField(blank=True, to='partediario.Inventario'),
        ),
        migrations.CreateModel(
            name='contratistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajos_realizados', models.CharField(max_length=50)),
                ('insumos', models.CharField(max_length=50)),
                ('parteDiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratista', to='partediario.partediario', verbose_name='Contratistas')),
            ],
        ),
    ]
