# Generated by Django 3.2.12 on 2022-04-27 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partediario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partediario',
            name='contratistas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.contratistas', verbose_name='Contratistas'),
        ),
        migrations.AlterField(
            model_name='partediario',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.entrada', verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='partediario',
            name='lluvia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.lluvia', verbose_name='Lluvias'),
        ),
        migrations.AlterField(
            model_name='partediario',
            name='opcionSanitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.opcionsanitacion', verbose_name='Opcion de Sanitacion'),
        ),
        migrations.AlterField(
            model_name='partediario',
            name='recategorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.recategorizacion', verbose_name='Recategorizacion'),
        ),
        migrations.AlterField(
            model_name='partediario',
            name='recorrida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.recorrida', verbose_name='Recorridas'),
        ),
        migrations.AlterField(
            model_name='partediario',
            name='rotacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.rotacion', verbose_name='Rotacion'),
        ),
        migrations.AlterField(
            model_name='partediario',
            name='salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.salida', verbose_name='Salida'),
        ),
        migrations.AlterField(
            model_name='partediario',
            name='sanitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.sanitacion', verbose_name='Sanitacion'),
        ),
        migrations.CreateModel(
            name='Capataz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('empresaCapataz', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Empresa', to='partediario.empresa', verbose_name='Empresa asociada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
