# Generated by Django 3.2.13 on 2022-05-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0002_auto_20220427_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='partediario',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
