# Generated by Django 3.2.13 on 2022-05-19 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0003_auto_20220510_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='cantidad_h',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='cantidad_m',
        ),
        migrations.RemoveField(
            model_name='otraactividad',
            name='parteDiario',
        ),
        migrations.RemoveField(
            model_name='partediario',
            name='opcionSanitacion',
        ),
        migrations.AddField(
            model_name='partediario',
            name='otra_actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.otraactividad', verbose_name='OtraotraActividad'),
        ),
        migrations.AlterField(
            model_name='partediario',
            name='fecha',
            field=models.DateField(),
        ),
    ]
