# Generated by Django 3.2.12 on 2022-03-01 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0003_auto_20220301_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entradas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salidas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('causa', models.CharField(max_length=50)),
                ('categoria_madre', models.ManyToManyField(to='partediario.Categoria')),
                ('parteDiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida', to='partediario.partediario', verbose_name='Salidas')),
                ('salida', models.ManyToManyField(to='partediario.Salidas')),
            ],
        ),
        migrations.AddField(
            model_name='entrada',
            name='entradas',
            field=models.ManyToManyField(to='partediario.Entradas'),
        ),
    ]
