# Generated by Django 3.2.12 on 2022-03-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0004_auto_20220301_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradas',
            options={'verbose_name_plural': 'Entradas'},
        ),
        migrations.AlterModelOptions(
            name='salidas',
            options={'verbose_name_plural': 'Salidas'},
        ),
    ]
