# Generated by Django 3.2.12 on 2022-03-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0005_auto_20220301_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salida',
            old_name='salida',
            new_name='salidas',
        ),
    ]
