# Generated by Django 3.2.13 on 2022-05-23 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0005_palpacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tractor', models.CharField(max_length=50, null=True)),
                ('insumo', models.CharField(max_length=50, null=True)),
                ('maquinaria', models.CharField(max_length=50, null=True)),
                ('causa', models.CharField(max_length=50, null=True)),
                ('hora_inicial', models.IntegerField(blank=True, null=True)),
                ('hora_final', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Palpacion',
            },
        ),
        migrations.AddField(
            model_name='partediario',
            name='palpacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partediario', to='partediario.palpacion', verbose_name='Palpacion'),
        ),
    ]
