# Generated by Django 3.2.13 on 2022-05-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0006_auto_20220523_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='has_utiles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Superficie',
        ),
    ]
