# Generated by Django 3.2.12 on 2022-03-01 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0006_rename_salida_salida_salidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='recategorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final', to='partediario.categoria', verbose_name='Recategorizacion Final')),
                ('categoria_inicial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inicial', to='partediario.categoria', verbose_name='Recategorizacion Inicial')),
                ('parteDiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recategorizacion', to='partediario.partediario', verbose_name='Recategorizacion')),
            ],
        ),
    ]
