# Generated by Django 3.2.13 on 2022-05-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0007_auto_20220524_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='pesoTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
