# Generated by Django 3.2.13 on 2022-05-31 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0008_salida_pesototal'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='opcionPeso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salida',
            name='opcionPeso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='destete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('pesoTotal', models.IntegerField(blank=True, null=True)),
                ('parteDiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destete', to='partediario.partediario', verbose_name='Destetes')),
            ],
        ),
    ]
