# Generated by Django 3.2.12 on 2022-03-01 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0008_recategorizacion_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franja', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='potreros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='potrero', to='partediario.potrero', verbose_name='Potreros'),
        ),
    ]
