# Generated by Django 3.2.13 on 2022-05-31 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0009_auto_20220531_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='opcionPeso',
            new_name='opcion_peso',
        ),
    ]
