# Generated by Django 3.2.12 on 2022-03-01 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0009_auto_20220301_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='rotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potrero_inicial', models.CharField(max_length=50)),
                ('potrero_final', models.CharField(max_length=50)),
                ('parteDiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotacion', to='partediario.partediario', verbose_name='Rotacion')),
            ],
        ),
        migrations.CreateModel(
            name='recorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potrero', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=120)),
                ('parteDiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorrida', to='partediario.partediario', verbose_name='Recorrida')),
            ],
        ),
    ]
