# Generated by Django 3.2.12 on 2022-03-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0010_recorrida_rotacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recategorizacion',
            options={'verbose_name_plural': 'Recategorizaciones'},
        ),
        migrations.AlterModelOptions(
            name='rotacion',
            options={'verbose_name_plural': 'Rotaciones'},
        ),
    ]
