# Generated by Django 3.2.13 on 2022-05-31 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0010_rename_opcionpeso_entrada_opcion_peso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='Inventario_de_Empresa',
            new_name='inventarios',
        ),
    ]
