# Generated by Django 3.2.12 on 2022-03-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0011_auto_20220301_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='potreros',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
