# Generated by Django 3.2.12 on 2022-03-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0013_opcionsanitacion_sanitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanitacion',
            name='categoria_madre',
        ),
        migrations.RemoveField(
            model_name='sanitacion',
            name='causa',
        ),
        migrations.AddField(
            model_name='sanitacion',
            name='observacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
