# Generated by Django 3.2.12 on 2022-03-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0014_auto_20220308_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='opcionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.AlterModelOptions(
            name='sanitacion',
            options={'verbose_name_plural': 'Sanitaciones'},
        ),
        migrations.CreateModel(
            name='pesaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('peso_minimo', models.IntegerField(blank=True, null=True)),
                ('peso_maximo', models.IntegerField(blank=True, null=True)),
                ('categoria', models.ManyToManyField(to='partediario.Categoria')),
                ('parteDiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesaje', to='partediario.partediario', verbose_name='Pesajes')),
            ],
        ),
        migrations.CreateModel(
            name='otraActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('categoria', models.ManyToManyField(to='partediario.Categoria')),
                ('opciones', models.ManyToManyField(to='partediario.opcionActividad')),
                ('parteDiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Otra', to='partediario.partediario', verbose_name='Otros')),
            ],
        ),
    ]
