# Generated by Django 3.2.12 on 2022-03-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0015_auto_20220308_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otraactividad',
            old_name='opciones',
            new_name='actividad_realizada',
        ),
    ]
