# Generated by Django 3.2.12 on 2022-03-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partediario', '0016_rename_opciones_otraactividad_actividad_realizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='contratistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajos_realizados', models.CharField(max_length=50)),
                ('insumos', models.CharField(max_length=50)),
                ('parteDiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratista', to='partediario.partediario', verbose_name='Contratistas')),
            ],
        ),
    ]
